# Site settings
name: Osman Sekerlen
email: contact.osmansekerlen@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Node JS, Javascript, Back End, Micro Services, Startups, Agile, Pair Programming"
skills: "Senior Software Engineer in New Jersey"
baseurl: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ozman/
  - title: github
    url: https://github.com/pegasuspect
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: cddc39 #2196F3
  primary-rgb: "205, 220, 57"
  secondary: 2e7d32 #285172
  secondary-dark: 1b5e20 #29455b
  section-tout: eaf1f1

# Build settings
markdown: kramdown
permalink: pretty
